Repository Seol-and-children/byeolbyeol-coffee-backend, pull requests merged in 2023-12, with the labels that each got.

#49 [Feature][User] User관련 수정본 1차)
  build.gradle
  src/main/java/com/seolandfriends/byeolbyeolcoffee/common/ResponseDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/config/BeanConfiguration.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/config/WebConfig.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/ApiExceptionAdvice.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/DuplicatedMemberEmailException.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/DuplicatedUserAccountException.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/DuplicatedUserEmailException.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/DuplicatedUserNickNameException.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/filter/HeaderFilter.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/handler/CustomAuthSuccessHandler.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/handler/TokenProvider.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/controller/AuthController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/controller/UserController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/TokenDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/UserDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/UserRoleDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/service/CustomUserDetailsService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/service/KakaoService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/service/UserService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/aggregate/entity/Role.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/aggregate/entity/User.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/aggregate/entity/UserRole.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/aggregate/entity/UserRolePK.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/repository/UserRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/repository/UserRoleRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/service/AuthService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/util/TokenUtils.java
  src/main/resources/application.yml
  src/test/java/com/seolandfriends/byeolbyeolcoffee/user/UserLoginTest.java
Labels: 🪲BugFix, 🆕Feature, 🖥️API

#53 [Feature][User] User관련 수정본 2차)
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/InvalidPasswordException.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/controller/AuthController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/controller/UserController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/TokenDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/UserDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/service/UserService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/repository/UserRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/service/AuthService.java
  src/main/resources/application.yml
Labels: 🪲BugFix, 🆕Feature, 🔨Refactoring

#57 [Feature][User] User관련 수정본 4차)
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/controller/AuthController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/controller/KakaoController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/controller/UserController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/UserDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/service/KakaoService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/service/UserService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/aggregate/entity/User.java
Labels: 🪲BugFix, 🆕Feature, 🖥️API

#58 커스텀 옵션 기능 수정 (스키마도 수정)
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/dto/RecipeCustomOptionDto.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/service/RecipeCommandService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/entity/Recipe.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/entity/RecipeCustomOption.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/repository/RecipeCustomOptionCommandRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/application/service/RecipeQueryService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/domain/repository/RecipeCustomOptionQueryRepository.java
Labels: 🆕Feature, 🛠️Fix
