Repository Seol-and-children/byeolbyeol-coffee-backend, pull requests merged in 2023-11, with the labels that each got.

#40 User all
  build.gradle
  src/main/java/com/seolandfriends/byeolbyeolcoffee/common/AuthConstants.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/common/ResponseDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/common/entity/BaseEntity.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/common/entity/BaseTimeEntity.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/common/entity/enumtype/Role.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/config/BeanConfiguration.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/config/JwtSecurityConfig.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/config/SecurityConfig.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/config/WebConfig.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/ApiExceptionAdvice.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/DuplicatedMemberEmailException.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/LoginFailedException.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/TokenException.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/exception/dto/ApiExceptionDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/filter/CustomAuthenticationFilter.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/filter/HeaderFilter.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/filter/JwtFilter.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/handler/CustomAuthFailureHandler.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/handler/CustomAuthSuccessHandler.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/handler/CustomAuthenticationProvider.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/jwt/handler/TokenProvider.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/controller/AuthController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/controller/UserController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/RoleDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/TokenDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/UserDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/dto/UserRoleDTO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/service/CustomUserDetailsService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/application/service/UserService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/aggregate/entity/Role.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/aggregate/entity/User.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/aggregate/entity/UserRole.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/aggregate/entity/UserRolePK.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/repository/UserRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/repository/UserRoleRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/user/command/domain/service/AuthService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/util/TokenUtils.java
  src/main/resources/application.properties
  src/test/java/com/seolandfriends/byeolbyeolcoffee/AuthControllerTest.java
  src/test/java/com/seolandfriends/byeolbyeolcoffee/ByeolByeolCoffeeApplicationTests.java
Labels: 🆕Feature

#44 [Fix][Recipe] 댓글 조회기능 수정
  build.gradle
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/controller/RecipeCommentController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/controller/RecipeLikeController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/dto/RecipeDto.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/service/RecipeCommentService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/service/RecipeLikeService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/service/RecipeService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/entity/Recipe.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/entity/RecipeComment.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/entity/RecipeLike.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/BaseBeverageVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/CommentUserVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/CustomOptionVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/FranchiseCafeVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/LikeUserVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/RecipeUserVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/repository/RecipeCommentRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/repository/RecipeLikeRepository.java
Labels: 🛠️Fix

#45 [Refactoring][Recipe] command/query 구분하여 구조 변경
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/controller/RecipeCommandController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/controller/RecipeCommentCommandController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/controller/RecipeLikeCommandController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/service/RecipeCommandService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/service/RecipeCommentCommandService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/service/RecipeLikeCommandService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/entity/Recipe.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/entity/RecipeComment.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/BaseBeverageVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/repository/RecipeCommandRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/repository/RecipeCommentCommandRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/repository/RecipeLikeCommandRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/application/controller/RecipeCommentQueryController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/application/controller/RecipeQueryController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/application/service/RecipeCommentQueryService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/application/service/RecipeQueryService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/domain/repository/RecipeCommentQueryRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/domain/repository/RecipeQueryRepository.java
  src/main/resources/static/recipeimgs/467f061d84a34186a1fbc1b34be5560e.png
  src/main/resources/static/recipeimgs/984226be08f94e3f86ae093e7279ea77.png
  src/test/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/controller/RecipeLikeCommandControllerTest.java
Labels: 🔨Refactoring

#48 [Fix][Recipe] 레시피 기능 수정
  build.gradle
  src/main/java/com/seolandfriends/byeolbyeolcoffee/config/BeanConfiguration.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/config/WebMvcConfig.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/controller/RecipeCommandController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/controller/RecipeCommentCommandController.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/dto/RecipeDto.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/application/service/RecipeCommentCommandService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/CommentUserVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/FranchiseCafeVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/LikeUserVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/aggregate/vo/RecipeUserVO.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/command/domain/repository/RecipeCommandRepository.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/application/service/RecipeQueryService.java
  src/main/java/com/seolandfriends/byeolbyeolcoffee/recipe/query/domain/repository/RecipeQueryRepository.java
Labels: 🛠️Fix
